export const GET_AGENTS = 'GET_AGENTS';
export const GET_COLLABORATOR_DATA = 'GET_COLLABORATOR_DATA';
export const GET_COLLABORATOR_WHATSAPP = 'GET_COLLABORATOR_WHATSAPP';
export const GET_COLLABORATOR_BANK = 'GET_COLLABORATOR_BANK';
export const COLLABORATOR_LOADING = 'COLLABORATOR_LOADING';
export const COLLABORATOR_LOADED = 'COLLABORATOR_LOADED';
