export const GET_DASHBOARD_WALLPAPER = 'GET_DASHBOARD_WALLPAPER';
export const GET_SUCCESS_RATE = 'GET_SUCCESS_RATE';
export const GET_USER_TICKETS = 'GET_USER_TICKETS';
export const GET_MONNIFY_ACCOUNT_LIST = 'GET_MONNIFY_ACCOUNT_LIST';
