export const GET_BALANCE = 'GET_BALANCE';
export const CREATE_VIRTUAL_ACCOUNT = 'CREATE_VIRTUAL_ACCOUNT';
export const DELETE_VIRTUAL_ACCOUNT = 'DELETE_VIRTUAL_ACCOUNT';
export const GET_VIRTUAL_ACCOUNT = 'GET_VIRTUAL_ACCOUNT';
export const GET_MOMO_AGENT_NUMBER = 'GET_MOMO_AGENT_NUMBER';
export const GET_ACCOUNT_NUMBER = 'GET_ACCOUNT_NUMBER';
export const GET_PAYMENT_STATUS = 'GET_PAYMENT_STATUS';
