export const GET_BALANCE = 'GET_BALANCE';
export const CREATE_VIRTUAL_ACCOUNT = 'CREATE_VIRTUAL_ACCOUNT';
export const DELETE_VIRTUAL_ACCOUNT = 'DELETE_VIRTUAL_ACCOUNT';
export const GET_VIRTUAL_ACCOUNT = 'GET_VIRTUAL_ACCOUNT';
