import {useNavigation, useRoute} from '@react-navigation/native';
import {
  Avatar,
  Box,
  Button,
  FormControl,
  Heading,
  Input,
  Text,
  VStack,
} from 'native-base';
import React, {useState} from 'react';
import Feather from 'react-native-vector-icons/Feather';
import {verifyMultiFactorOtp} from '../../api';
import {LOGIN_SUCCESS} from '../../redux/constants/auth';
import {Alert} from 'react-native';
import {useDispatch} from 'react-redux';

export const OAuthVerificationScreen = () => {
  const navigation = useNavigation();

  const data = useRoute().params?.data;

  const [otp, setOtp] = useState('');
  const [loading, setLoading] = useState(false);
  const dispatch = useDispatch();

  const handleVerifyMultifactor = async () => {
    setLoading(true);

    const request = await verifyMultiFactorOtp(otp, data?.token);
    if (request.ok) {
      dispatch({type: LOGIN_SUCCESS, payload: data});
      setLoading(false);
      return;
    }

    setLoading(false);
    Alert.alert(request.data?.message);
  };

  return (
    <Box flex={1} justifyContent={'center'} alignItems={'center'}>
      <Heading>Verify your identity</Heading>
      <VStack
        px={'4'}
        space={'2'}
        mt={'2'}
        alignItems={'center'}
        width={'100%'}>
        <Text textAlign={'center'}>
          To keep your account secure, Enter the code generated by your
          authenticator app.
        </Text>
        <Avatar mt="4">
          <Feather name={'user'} color={'white'} size={20} />
        </Avatar>
        <Text>{`${data?.user?.first_name} ${data?.user?.last_name}`}</Text>
        <FormControl width={'full'}>
          <FormControl.Label>Verification Code</FormControl.Label>
          <Input
            width={'full'}
            value={otp}
            size={'lg'}
            py={'3'}
            onChangeText={text => setOtp(text)}
            placeholder="Verification Code"
          />
        </FormControl>
        <Button
          onPress={handleVerifyMultifactor}
          isLoading={loading}
          mt={'2'}
          width={'100%'}
          size={'lg'}>
          Verify
        </Button>
        <Button
          onPress={() => navigation.goBack()}
          variant={'outline'}
          isDisabled={loading}
          mt={'2'}
          width={'100%'}
          size={'lg'}>
          Cancel
        </Button>
      </VStack>
    </Box>
  );
};
